<p>
Slickgrid Index
</p>



<script src="/phpslickgrid/js/json/jquery.zend.jsonrpc.js"></script>
<script>

var service = new jQuery.Zend.jsonrpc({
	url : "/demo/slickgrid/rpc",
	async : false,
	//'error': function(data) {alert(data);inFlight=0;}, //
	// Connection error
	'error' : function(data) {
		console.log(data);
		//alert(data.error_request.responseText);
		//alert('The connection to the server has timed out. Click OK to try again.');
		// inFlight = 0;
	}, // Connection error
	'exceptionHandler' : function(data) {
		alert(data);
		onInvalidate.notify();
	}
}); // thrown exception.
var t = service.getData(1);
console.log(t);

</script>